### ISSUE TITLE
ae0 interface error 

### ISSUE THREAD

**Issue by kuki21** [JNPRAutomate/fluent-plugin-juniper-telemetry#2]
Hi 

I notice that plugin parser_juniper_jti.rb is not working earn you have ae0 interface. I have add this simple  workaround and now it is collecting and paring data. 

In line 93
if data == 'ae0'
                                        $log.warn "err-ae0 '#{data}'"
                                     else
                                      data.each do |type,value|

Is this something you can fix to collect data from ae0 interfaces ?

**Comment by dgarros** [comment]
Hi

Thanks for the feedback
Could you provide a pcap file that contain an AE interface, I'll work on a solution
Also I'm planning to add unittest to this repo soon, it will be very useful

Thanks
Damien

**Comment by kuki21** [comment]
Hi Damian

Sorry for this late reply. pcap file in attachment.

Lukasz

2016-03-09 20:03 GMT+01:00 Damien notifications@github.com:

**Comment by dgarros** [comment]
Hi 

Sorry for the delay and thanks for providing the file
I fixed the issue with AE interface, please can you give it a try

Thanks
Damien

**Comment by dgarros** [comment]
Close since it's been fixed for a while
